steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-Dmaven.test.skip=true' , '-frestaurant-msa/pom.xml'] # added the step to build the jar
    id: 'maven-build'
  - name: 'gcr.io/cloud-builders/docker'
    id: 'image-build'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/cloud-next25-screendemo/cloud-next25-screendemo/restaurants-api', '--build-arg=JAR_FILE=target/restaurants-0.1.jar', './restaurant-msa']
    waitFor: ['maven-build'] # Wait for the Maven build to complete
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us-central1-docker.pkg.dev/cloud-next25-screendemo/cloud-next25-screendemo/restaurants-api' ]
    waitFor: ['maven-build', 'image-build']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'restaurants-api'
    - '--image'
    - 'us-central1-docker.pkg.dev/cloud-next25-screendemo/cloud-next25-screendemo/restaurants-api'
    - '--region'
    - 'us-central1'
    - '--concurrency'
    - '80'
    - '--max-instances'
    - '4'
    - '--min-instances'
    - '1'
    - '--timeout'
    - '300'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'GOOGLE_CLOUD_PROJECT=cloud-next25-screendemo'
    waitFor: [ 'maven-build' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'services'
    - 'add-iam-policy-binding'
    - 'restaurants-api'
    - '--region'
    - 'us-central1'
    - '--member'
    - 'allUsers'
    - '--role'
    - 'roles/run.invoker'
    waitFor: [ 'maven-build' ]
images:
- 'us-central1-docker.pkg.dev/cloud-next25-screendemo/cloud-next25-screendemo/restaurants-api'
options:
    logging: CLOUD_LOGGING_ONLY